# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Sziasztok
  displayName: 'Köszönés'

- script: |
    env
    sudo apt update
    sudo apt upgrade -y 
  displayName: 'Ubuntu frissítés'
